@extends('layouts.skeleton')
@section('title', 'QR CODE List')
@section('content')
    <div class="app-content main-content">
        <div class="side-app main-container">
            <div class="page-header d-xl-flex d-block">
                <div class="page-leftheader">
                    <div class="page-title">QR CODE List</div>
                </div>
                <div class="page-rightheader ms-md-auto">
                    <div class="d-flex align-items-end flex-wrap my-auto end-content breadcrumb-end">
                        {{-- <div class="btn-list">
                            <a href="{{ url()->previous() }}" class="btn btn-primary"> <i class="fa fa-arrow-left"></i> Go Back </a>
                        </div> --}}
                    </div>
                </div>
            </div>



            <div class="row row-sm">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">QR CODE List</h3>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered text-nowrap border-bottom" id="basic-datatable">
                                    <thead>
                                        <tr>
                                            <th class="wd-15p border-bottom-0">SL</th>
                                            <th class="wd-15p border-bottom-0">Title</th>
                                            <th class="wd-15p border-bottom-0">Entry Date</th>
                                            <th class="wd-15p border-bottom-0">Reference No</th>
                                            <th class="wd-15p border-bottom-0">Generated By</th>
                                            @if (auth()->user()->user_type != 3)
                                                <th class="wd-15p border-bottom-0">Secret Token</th>
                                            @endif
                                            {{-- <th class="wd-15p border-bottom-0">Department</th> --}}
                                            <th class="wd-15p border-bottom-0">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($data as $item)
                                            <tr>
                                                <th scope="row">{{ $loop->iteration }}</th>
                                                <td>{{ $item->title }}</td>
                                                <td>{{ $item->issue_date ? \Carbon\Carbon::parse($item->issue_date)->format('Y-m-d') : null }}
                                                </td>
                                                <td>{{ $item->ref_no }}</td>
                                                <td>{{ $item->user->username }}</td>
                                                @if (auth()->user()->user_type != 3)
                                                    <td onclick="secret_token({{ $item->id }})" style="cursor: pointer"
                                                        data-bs-toggle="modal" data-bs-target="#exampleModal2"
                                                        data-bs-toggle="tooltip" data-bs-placement="top" title="Token">
                                                        @php
                                                            echo substr($item->token, 0, 2) . '******' . substr($item->token, 8, 3);
                                                        @endphp

                                                    </td>
                                                @endif
                                                {{-- <td>{{ $item->department->title ?? null }}</td> --}}
                                                <td>
                                                    <a href="" data-id="{{ $item->id }}"
                                                        data-info="{{ $item->user->username }}"
                                                        data-image="{{ asset($item->image) }}" data-bs-toggle="modal"
                                                        data-bs-target="#exampleModal"
                                                        class="btn btn-warning btn-sm preview-image">
                                                        <i data-bs-toggle="tooltip" data-bs-placement="top" title="Preview"
                                                            class="fa fa-eye"></i>
                                                    </a>
                                                    <a href="{{ route('qr.edit', $item->id) }}"
                                                        class="btn btn-primary btn-sm">
                                                        <i data-bs-toggle="tooltip" data-bs-placement="top" title="Edit"
                                                            class="fa fa-edit"></i>
                                                    </a>
                                                    @if (auth()->user()->user_type != 3)
                                                        <a onclick="deleteConfirm({!! $item->id !!},'{{ route('qr.destroy', $item->id) }}')"
                                                            class="btn btn-danger btn-sm">
                                                            <i data-bs-toggle="tooltip" data-bs-placement="top"
                                                                title="Delete" class="fa fa-trash"></i>
                                                        </a>
                                                    @endif

                                                    <a href="{{ route('printable', $item->id) }}"
                                                        class="btn btn-success btn-sm" target="_blank">
                                                        <i data-bs-toggle="tooltip" data-bs-placement="top" title="Print"
                                                            class="fa fa-print"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="6">No Data Found</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @include('staff.qr.preview')
    </div>
@endsection
@section('scripts')
    <script>
        $(".preview-image").on('click', function() {
            $("#qr_image").attr('src', $(this).data('image'))
            $("#qr_info").text(`Generated By: ${$(this).data('info')} | bcsir-ctg#${$(this).data('id')}`)
        })
    </script>

@if (auth()->user()->user_type != 3)
    <script>
        function secret_token(id) {
            $("#qr_id").val(id)
        }
        $(".token_view").on('click', function() {
            let pass = $("#password").val();
            let qr_id = $("#qr_id").val();
            $(".append-grp").html("");
            $.ajax({
                type: "POST",
                url: '{{ route('qr.token_view') }}',
                data: {
                    pass: pass,
                    qr_id: qr_id,
                    _token: "{{ csrf_token() }}"
                },
                success: function(response) {
                    if (response == 0) {
                        $(".error").text('Password not matched.')
                    } else {
                        $(".error").text('');
                        let html = `
                                    <label class="form-label">Your Secret Token</label>
                                    <div class="input-group mb-4">
                                        <div class="input-group">
                                            <a href="" class="input-group-text">
                                                <i class="fe fe-aperture" aria-hidden="true"></i>
                                            </a>
                                            <input class="form-control" id="secret_token" type="text" value="${response}" placeholder="Secret Token" readonly>  
                                        </div>   
                                    </div>`;
                        $(".append-grp").html(html);
                        $('.token_view').attr('disabled', '');
                        $("#password").attr('readonly', '');
                    }
                }
            })
        })

        $(".closeModal").on('click', function() {
            $(".append-grp").html("");
            $('#password').val('')
            $('.token_view').removeAttr('disabled')
            $('#password').removeAttr('readonly')
        })
    </script>
@endif
@endsection
